### ISSUE TITLE
Broken Text in README.md

### ISSUE THREAD

**Issue by DeeBi9** [OpenTechTools/Share-Spreader#1]
Modify README.md according to the project tech stack and resolve the text issues

**Comment by Mohiit70** [comment]
> Modify README.md according to the project tech stack and resolve the text issues

Alright, I will update the tech stack and fix the broken parts. Can you share a brief overview of the tech stack framework we're using for the project ?

**Comment by DeeBi9** [comment]
Tech stack include :

Golang for backend microservices and api integration
grpc for inter-service communication between different services 
plain html and css for frontend
