### ISSUE TITLE
Create a separate branch before opening the PR

### ISSUE THREAD

**Issue by DeeBi9** [OpenTechTools/Share-Spreader#2]
@Mohiit70 , The changes we as individual makes should be in separate branches to avoid the conflicts . I faced some problems earlier so make sure we do that

**Comment by Mohiit70** [comment]
> @Mohiit70 , The changes we as individual makes should be in separate branches to avoid the conflicts . I faced some problems earlier so make sure we do that

Got it. From now onward, we will create separate branches for every service, etc.
